import numpy as np
import pandas as pd
import codecademylib3
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import LinearSVC
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

# ---------------
# Task 1: Drop nan values.
# ---------------

# Read the csv data as a DataFrame
df = pd.read_csv('./telescope_data.csv', index_col=0)

# Remove null and na values
df.dropna()

# Print the DataFrame head
#print('Task 1:')
#print(df.head())

# ---------------
# Task 2: Extract class column.
# ---------------
# Extract the class classes
classes = df['class']
data_matrix = df.drop(columns='class')

#print('Task 2:')
#print(data_matrix)

# ---------------
# Task 3: Create a correlation matrix.
# ---------------
# Use the `.corr()` method on `data_matrix` to get the correlation matrix 
correlation_matrix = data_matrix.corr()

# ax = plt.axes()
# sns.heatmap(correlation_matrix, cmap='Greens', ax=ax)
# ax.set_title('Task 3:')
# plt.show()

# ---------------
# Task 4: Perform eigendecomposition.
# ---------------

#print('Task 4:')
# Perform eigendecomposition using `np.linalg.eig` 
eigenvalues, eigenvectors = np.linalg.eig(correlation_matrix)

# print(f'Eigenvalues length: {eigenvalues.size}, Original Number of Features: {data_matrix.shape[1]}')

# Order the eigenvalues by ordering the indices of the eigenvalues using `argsort`, and use [::-1] to order them from greatest to smallest
indices = eigenvalues.argsort()[::-1]  
eigenvalues = eigenvalues[indices]
eigenvectors = eigenvectors[:, indices]

# print(eigenvalues.shape, eigenvectors.shape)

# ---------------
# Task 5: Find the variance/information percentages for each eigenvalue.
# ---------------
# Find the percentages of information for each eigenvector, which is generated by the proportion of its eigenvalues to the sum of all eigenvalues
information_proportions = eigenvalues / eigenvalues.sum()
information_percents = information_proportions * 100

# Plot the principal axes vs the information proportions for each principal axis
# plt.figure()
# plt.plot(information_percents, 'ro-', linewidth=2)
# plt.title('Task 5: Scree Plot')
# plt.xlabel('Principal Axes')
# plt.ylabel('Percent of Information Explained')
# plt.show()

# ---------------
# Task 6: Find the cumulative variance/information percentages for each eigenvalue.
# ---------------
# Find the cumulative sum of the percentages
cumulative_information_percents = np.cumsum(information_percents)

# Plot the cumulative percentages array
# plt.figure()
# plt.plot(cumulative_information_percents, 'ro-', linewidth=2)

# Also plot a horizontal line indicating the 95% mark, and a vertical line for the third principal axis
# plt.hlines(y=95, xmin=0, xmax=15)
# plt.vlines(x=3, ymin=0, ymax=100)
# plt.title('Task 6: Cumulative Information percentages')
# plt.xlabel('Principal Axes')
# plt.ylabel('Cumulative Proportion of Variance Explained')
# plt.show()


#PCA-----------------------
#7:
mean = np.mean(data_matrix, axis=0)
std = np.std(data_matrix, axis=0, ddof=1)

data_matrix_standardized = (data_matrix - mean) / std

#8:
pca=PCA()
data_pca = pca.fit_transform(data_matrix) 

#9:
eigenvalue = pca.singular_values_
eigenvector = pca.components_.T

# print(eigenvalue)
# print(eigenvector)

#10:
var_ratios = pca.explained_variance_ratio_
print(var_ratios)

pca=PCA(n_components = 2)
data_pca = pca.fit_transform(data_matrix) 

data_pca_df = pd.DataFrame(data_pca, columns=["PC1", "PC2"])
data_pca_df["class"] = classes.values 

sns.lmplot(x='PC1', y='PC2', data=data_pca_df, fit_reg=False, hue='class', scatter_kws={'alpha': 0.5})
plt.plot()
plt.show()

#13:
# Fit the transformed features onto the classifier and generate a score.
# ---------------
# Get principal components with 2 features 
# Perform PCA using 2 components
pca_1 = PCA(n_components=2) 
 
y = classes.astype('category').cat.codes

# Use the principal components as X and split the data into 33% testing and the rest training
X = pca_1.fit_transform(data_matrix_standardized) 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
 
# Create a Linear Support Vector Classifier
svc_1 = LinearSVC(random_state=0, tol=1e-5)
svc_1.fit(X, y) 
 
# Generate a score for the testing data
score_1 = svc_1.score(X_test, y_test)
print(f'Score for model with 2 PCA features: {score_1}')

# 14:
# Using the original features 
# Select two features from the original data
first_two_original_features = [0, 1]
X_original = data_matrix_standardized.iloc[:, first_two_original_features]
 
# Split the data intro 33% testing and the rest training
X_train, X_test, y_train, y_test = train_test_split(X_original, y, test_size=0.33, random_state=42)
 
# Create a Linear Support Vector Classifier
svc_2 = LinearSVC(random_state=0)
svc_2.fit(X_train, y_train)
 
# Generate a score for the testing data
score_2 = svc_2.score(X_test, y_test)
print(f'Score for model with 2 original features: {score_2}')



* You perform standardization, PCA, and training, which is good. Minor inefficiencies exist (recomputing data_matrix_standardized vs reusing; fitting PCA twice).
* Improve by properly standardizing once, reuse standardized data for all PCA runs, and avoid fitting PCA on unstandardized data.
* Use a single train/test split and reuse the transformed features for both PCA-based and original-feature classifiers to compare scores efficiently.
